# Generated by Django 4.1 on 2025-09-20 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grade", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, unique=True, verbose_name="学籍号"),
                ),
                ("student_name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女")],
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        help_text="格式例如：2025-05-01", verbose_name="出生日期"
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(max_length=20, verbose_name="联系方式"),
                ),
                ("address", models.TextField(verbose_name="家庭住址")),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="grade.grade",
                        verbose_name="班级",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生信息",
                "verbose_name_plural": "学生信息",
                "db_table": "student",
            },
        ),
    ]
