# Generated by Django 4.1 on 2025-09-20 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grade", "0001_initial"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="grade.grade",
                verbose_name="班级",
            ),
        ),
    ]
