# Generated by Django 4.1 on 2025-09-29 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grade", "0002_grade_teachers"),
        ("student", "0002_alter_student_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="grade.grade",
                verbose_name="班级",
            ),
        ),
    ]
