# Generated by Django 4.1 on 2025-09-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
        ("grade", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="teachers",
            field=models.ManyToManyField(to="teacher.teacher"),
        ),
    ]
