# Generated by Django 4.1 on 2025-09-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女")],
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        help_text="格式例如：2025-05-01", verbose_name="出生日期"
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(max_length=20, verbose_name="联系方式"),
                ),
                ("address", models.TextField(verbose_name="家庭住址")),
            ],
            options={
                "verbose_name": "教师信息",
                "db_table": "Teacher",
            },
        ),
    ]
