# Generated by Django 5.2 on 2025-10-24 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name": "教师信息", "verbose_name_plural": "教师信息"},
        ),
    ]
